// prettier-ignore
/* eslint-disable */
// This file is autogenerated by script.
// Do not modify manually.
    
export const sourceCodeLang = 'ru_RU'

export const supportedLanguages = ["en_US","ru_RU"]
