import fs from 'fs/promises'
import path from 'path'
import { sourceCodeLang, supportedLanguages } from './asset-lang.js'

/** @template T */
class LangWriter {
  /** @type {string} */
  base

  /** @type {(data: Record<string, T>) => string} */
  stringify = data => JSON.stringify(data, null, 2)

  parse = JSON.parse

  /** @type {Record<string, Record<string, T>>} */
  storage = {}

  constructor(base = 'lang') {
    this.base = base
  }

  ext = '.json'

  /** @param {string} lang */
  #path(lang) {
    return path.join(this.base, lang + this.ext)
  }

  readAll() {
    return Promise.all(supportedLanguages.map(e => this.read(e)))
  }

  writeAll() {
    return Promise.all(supportedLanguages.map(e => this.write(e)))
  }

  unusedWarn = new Set()

  /**
   * @param {string} lang
   * @param {Record<string, T>} data
   */
  write(lang, data = { ...this.storage[sourceCodeLang], ...this.storage[lang] }) {
    for (const key in data) {
      const value = data[key]
      if (!(key in this.storage[sourceCodeLang])) {
        if (!this.unusedWarn.has(key)) {
          this.unusedWarn.add(key)
          console.warn(this.prefix, lang, 'Unused key', key)
        }
      } else {
        const expected = this.storage[sourceCodeLang][key]
        if (
          !(
            (typeof value === 'string' && typeof expected === 'string') ||
            (typeof value === 'object' && typeof expected === 'object')
          )
        ) {
          console.warn(
            `${this.prefix}: Unexpected type of message with id ${key} for lang ${lang}`,
            value,
            'expected:',
            expected,
          )
        }
      }
    }
    return fs.writeFile(this.#path(lang), (this.stringify(data) + '\n').replaceAll('\n', '\r\n'), 'utf-8')
  }

  get prefix() {
    return `LangWriter(${this.base}/*.${this.ext})`
  }

  /**
   * @param {string} lang
   * @returns {Promise<Record<string, T>>}
   */
  async read(lang) {
    /** @type {Record<string, T>} */
    let parsed = {}

    try {
      parsed = this.parse(await fs.readFile(this.#path(lang), 'utf-8'))
    } catch (e) {
      console.warn('Unable to read lang', lang, 'with base', this.base, e)
    }

    if (lang === sourceCodeLang) {
      this.storage[lang] = parsed
    } else {
      this.storage[lang] = {
        ...parsed,
        ...(this.storage[lang] ?? {}),
      }
    }

    console.log(`${this.prefix}:`, 'Read', lang, 'with keys', Object.keys(parsed).length)

    return parsed
  }
}

/** @typedef {string | Record<string, string>} Message */
/** @type {LangWriter<Message>} */
export const messagesJson = new LangWriter('lang')

/** @type {LangWriter<string>} */
export const sharedMessages = new LangWriter('texts')
sharedMessages.ext = '.lang'
sharedMessages.stringify = data => {
  let t = '### This file is autogenerated, do not edit\n\n'
  for (const k in data) t += `${k}=${data[k].replaceAll('\\n', '~LINEBREAK~')}\n`
  return t
}
sharedMessages.parse = () => ({}) // .lang files are output only, source of truth is JSON

export async function readMessages() {
  await sharedMessages.readAll()
  await messagesJson.readAll()
}

/**
 * @template {Record<string, unknown>} T
 * @template {string} K2
 * @template V2
 * @param {T} object
 * @param {(key: keyof T, value: Required<T>[keyof T], object: NoInfer<T>) => [K2, V2] | false} mapper
 * @returns {NoInfer<Record<K2, V2>>}
 */
function map(object, mapper) {
  /** @type {Record<string, unknown>} */
  const result = {}
  for (const key of Object.getOwnPropertyNames(object)) {
    // @ts-expect-error
    const mapped = mapper(key, object[key], object)
    if (mapped) result[mapped[0]] = mapped[1]
  }
  // @ts-expect-error
  return result
}

export async function writeMessages() {
  await sharedMessages.writeAll()
  await messagesJson.writeAll()

  const transformedMessages = map(messagesJson.storage, (lang, messages) => [
    lang,
    map(messages, (id, value) => {
      if (typeof value === 'string') return [id, value]
      return false
    }),
  ])

  const transformedPlurals = map(messagesJson.storage, (lang, messages) => [
    lang,
    map(messages, (id, value) => {
      if (typeof value === 'object' && !Array.isArray(value)) return [id, value]
      return false
    }),
  ])

  const sharedIds = Object.fromEntries(
    Object.entries(sharedMessages.storage[sourceCodeLang]).map(([id, token]) => [id, templateToSharedId(id)]),
  )

  await fs.writeFile(
    path.join('src/lib/assets', 'lang-messages.ts'),
    `
/* eslint-ignore */
/* i18n-ignore */
// Autogenerated by translate plugin

type Language = string
type MessageId = string

export const extractedSharedMessagesIds: Record<MessageId, string> = ${JSON.stringify(sharedIds, null, 2)}

export const extractedTranslatedMessages: Record<Language, Record<MessageId, string>> = ${JSON.stringify(transformedMessages, null, 2)}

export const extractedTranslatedPlurals: Record<Language, Record<MessageId, Record<string, string>>> = ${JSON.stringify(transformedPlurals, null, 2)}
`.replaceAll('\\\\n', '\\n'),
  )
}

/** @param {string} id - The placeholder-based message ID, e.g. "Выше {0_y} и ниже {1_x}" */
function templateToSharedId(id) {
  return (
    'script.shared.' +
    id
      .toLowerCase()
      .replace(/§./g, '')
      .replace(/\{(\d+)(?:_\w+)?\}/g, '_$1_')
      .replace(/[^a-zA-Zа-яА-Я.$_0-9]/g, '_')
      .replace(/\.+/g, '.')
      .replace(/_+/g, '_')
  )
}

const plurals = Object.fromEntries(
  supportedLanguages.map(e => [e, new Intl.PluralRules(e.replace('_', '-')).resolvedOptions().pluralCategories]),
)

/**
 * Adds or updates a translation entry.
 *
 * @param {string} id - The message ID with placeholders, e.g. "Вы добыли {0_amount} из {1_needed}"
 * @param {boolean} shared - Whether the message is an i18nShared tagged template
 * @param {boolean} plural - Whether the message is an i18nPlural tagged template
 */
export function addTranslation(id, shared, plural) {
  const sourcePrev = messagesJson.storage[sourceCodeLang][id]

  if (plural) {
    const sourceCategories = plurals[sourceCodeLang]
    const defaultPlurals = Object.fromEntries(sourceCategories.map(c => [c, id]))
    messagesJson.storage[sourceCodeLang][id] = {
      ...defaultPlurals,
      ...(sourcePrev && typeof sourcePrev === 'object' && !Array.isArray(sourcePrev) ? sourcePrev : {}),
    }
  } else {
    messagesJson.storage[sourceCodeLang][id] = id
  }

  for (const lang of supportedLanguages) {
    if (lang === sourceCodeLang) continue

    const prev = messagesJson.storage[lang][id]
    if (plural) {
      if (prev === undefined || (typeof prev === 'object' && !Array.isArray(prev))) {
        const langCategories = plurals[lang]
        const defaultPlurals = Object.fromEntries(langCategories.map(c => [c, id]))
        messagesJson.storage[lang][id] = {
          ...defaultPlurals,
          ...(typeof prev === 'object' ? prev : {}),
        }
      } else {
        throw new Error(`Plural key conflict for ${id} in ${lang}`)
      }
    } else {
      if (prev === undefined) messagesJson.storage[lang][id] = id
    }
  }

  if (shared || plural) {
    for (const lang of supportedLanguages) {
      const translation = messagesJson.storage[lang][id]
      if (typeof translation === 'string') {
        sharedMessages.storage[lang][id] = translation.replace(/\{(\d+)(?:_\w+)?\}/g, '%s')
      } else if (translation && typeof translation === 'object') {
        for (const rule in translation) {
          sharedMessages.storage[lang][`${id}.${rule}`] = translation[rule].replace(/\{(\d+)(?:_\w+)?\}/g, '%s')
        }
      }
    }
  }
}
