import fs from 'fs/promises'
import path from 'path'
import { sourceCodeLang, supportedLanguages } from './asset-lang.js'

/** @template T */
class LangWriter {
  /** @type {string} */
  base

  /** @type {(data: Record<string, T>) => string} */
  stringify = data => JSON.stringify(data, null, 2)

  parse = JSON.parse

  /** @type {Record<string, Record<string, T>>} */
  storage = {}

  /** @param {string} [base='lang'] . Default is `'lang'` */
  constructor(base = 'lang') {
    this.base = base
  }

  ext = '.json'

  /**
   * @param {string} lang
   * @returns {string}
   */
  #path(lang) {
    return path.join(this.base, lang + this.ext)
  }

  /** @returns {Promise<Record<string, Record<string, T>>>} */
  readAll() {
    return Promise.all(supportedLanguages.map(e => this.read(e))).then(() => this.storage)
  }

  /** @returns {Promise<void[]>} */
  writeAll() {
    return Promise.all(supportedLanguages.map(e => this.write(e)))
  }

  /** @type {Set<string>} */
  unusedWarn = new Set()

  /**
   * @param {string} lang
   * @param {Record<string, T>} [data]
   * @returns {Promise<void>}
   */
  write(lang, data = { ...this.storage[sourceCodeLang], ...this.storage[lang] }) {
    for (const key in data) {
      const value = data[key]
      if (!(key in this.storage[sourceCodeLang])) {
        if (!this.unusedWarn.has(key)) {
          this.unusedWarn.add(key)
          console.warn(this.prefix, lang, 'Unused key', key)
        }
      } else {
        const expected = this.storage[sourceCodeLang][key]
        if (
          !(
            (typeof value === 'string' && typeof expected === 'string') ||
            (typeof value === 'object' && typeof expected === 'object')
          )
        ) {
          console.warn(
            `${this.prefix}: Unexpected type of message with id ${key} for lang ${lang}`,
            value,
            'expected:',
            expected,
          )
        }
      }
    }
    return fs.writeFile(this.#path(lang), (this.stringify(data) + '\n').replaceAll('\n', '\r\n'), 'utf-8')
  }

  /** @returns {string} */
  get prefix() {
    return `LangWriter(${this.base}/*.${this.ext})`
  }

  /**
   * @param {string} lang
   * @returns {Promise<Record<string, T>>}
   */
  async read(lang) {
    /** @type {Record<string, T>} */
    let parsed = {}

    try {
      parsed = this.parse(await fs.readFile(this.#path(lang), 'utf-8'))
    } catch (e) {
      console.warn('Unable to read lang', lang, 'with base', this.base, e)
    }

    if (lang === sourceCodeLang) {
      this.storage[lang] = parsed
    } else {
      this.storage[lang] = {
        ...parsed,
        ...(this.storage[lang] ?? {}),
      }
    }

    console.log(`${this.prefix}:`, 'Read', lang, 'with keys', Object.keys(parsed).length)

    return parsed
  }
}

/** @typedef {string | Record<string, string>} Message */

/** @type {LangWriter<Message>} */
export const messagesJson = new LangWriter('lang')

/** @type {LangWriter<string>} */
export const sharedMessages = new LangWriter('texts')
sharedMessages.ext = '.lang'
sharedMessages.stringify = /** @param {Record<string, string>} data */ data => {
  let t = '### This file is autogenerated, do not edit\n\n'
  for (const k in data) {
    const token = templateToSharedId(k)
    const value = data[k].replaceAll('\\n', '~LINEBREAK~')
    t += `${token}=${value}\n`
  }
  return t
}
sharedMessages.parse = () => ({})

/** @returns {Promise<void>} */
export async function readMessages() {
  await sharedMessages.readAll()
  await messagesJson.readAll()
}

function cleanTranslations() {
  deduplicateAndMergeAllLanguages()

  const source = messagesJson.storage[sourceCodeLang]
  for (const lang of supportedLanguages) {
    if (lang === sourceCodeLang) continue
    const target = messagesJson.storage[lang]
    for (const key in target) {
      if (!(key in source)) {
        delete target[key]
        console.log(`Removed unused key ${key} from ${lang}`)
      }
    }
  }
}

function deduplicateAndMergeAllLanguages() {
  const placeholderRegex = /\{(\d+)(?:_\w+)?\}/g
  /**
   * @param {string} key
   * @returns {string}
   */
  const normalize = key => key.replace(placeholderRegex, (_, index) => `{${index}}`)

  /** @type {Record<string, string[]>} */
  const allGroups = {}

  for (const lang of supportedLanguages) {
    const data = messagesJson.storage[lang]
    for (const key in data) {
      const norm = normalize(key)
      if (!allGroups[norm]) allGroups[norm] = []
      if (!allGroups[norm].includes(key)) allGroups[norm].push(key)
    }
  }

  /** @type {Record<string, string>} */
  const canonicalKeyMap = {}
  /** @type {Record<string, Record<string, string>>} */
  const languageCanonicalMap = {}

  for (const norm in allGroups) {
    const keys = allGroups[norm]

    // Improved canonical selection: prefer the key with the most underscores in its placeholders
    /**
     * @param {string} k
     * @returns
     */
    const countUnderscores = k =>
      (k.match(/\{(\d+)_(\w+)\}/g) || []).reduce((sum, p) => sum + (p.split('_').length - 1), 0)
    keys.sort((a, b) => countUnderscores(b) - countUnderscores(a))
    const canonicalKey = keys[0]

    canonicalKeyMap[norm] = canonicalKey

    languageCanonicalMap[norm] = {}
    for (const lang of supportedLanguages) {
      const langData = messagesJson.storage[lang]
      // Pick the canonical key if present, otherwise fallback to the first key present
      const presentKeys = keys.filter(k => k in langData)
      const canonicalHere = presentKeys.find(k => k === canonicalKey) || presentKeys[0] || canonicalKey
      languageCanonicalMap[norm][lang] = canonicalHere
    }
  }

  // Merge translations
  for (const lang of supportedLanguages) {
    const langData = messagesJson.storage[lang]
    for (const norm in canonicalKeyMap) {
      const canonical = languageCanonicalMap[norm][lang]
      if (!(canonical in langData)) continue

      const canonicalVal = langData[canonical]
      const isDefault =
        (typeof canonicalVal === 'string' && canonicalVal === canonical) ||
        (typeof canonicalVal === 'object' &&
          canonicalVal !== null &&
          JSON.stringify(canonicalVal) === JSON.stringify(defaultPluralForCanonical(canonical)))

      if (!isDefault) continue

      const otherKeys = allGroups[norm].filter(k => k in langData && k !== canonical)
      for (const other of otherKeys) {
        const otherVal = langData[other]
        const otherIsDefault =
          (typeof otherVal === 'string' && otherVal === other) ||
          (typeof otherVal === 'object' &&
            otherVal !== null &&
            JSON.stringify(otherVal) === JSON.stringify(defaultPluralForCanonical(other)))

        if (!otherIsDefault) {
          if (typeof otherVal === 'string') {
            langData[canonical] = otherVal
            console.log(`[${lang}] Copied translation from "${other}" to "${canonical}"`)
          } else if (typeof otherVal === 'object' && otherVal !== null) {
            langData[canonical] = { ...otherVal }
            console.log(`[${lang}] Copied plural translation from "${other}" to "${canonical}"`)
          }
          break
        }
      }
    }
  }

  // Remove all non‑canonical keys
  for (const lang of supportedLanguages) {
    const langData = messagesJson.storage[lang]
    for (const key in langData) {
      const norm = normalize(key)
      if (norm in canonicalKeyMap && key !== languageCanonicalMap[norm][lang]) {
        delete langData[key]
        console.log(`[${lang}] Removed duplicate key "${key}"`)
      }
    }
  }
}

/**
 * @param {string} key
 * @returns {Record<string, string>}
 */
function defaultPluralForCanonical(key) {
  const rules = plurals[sourceCodeLang]
  /** @type {Record<string, string>} */
  const obj = {}
  for (const rule of rules) {
    obj[rule] = key
  }
  return obj
}

/**
 * Pre‑process a placeholder string into { s: string[], i: number[] }
 *
 * @param {string} str
 * @returns {{ s: string[]; i: number[] }}
 */
function preprocessPlaceholderString(str) {
  /** @type {string[]} */
  const segments = []
  /** @type {number[]} */
  const indices = []
  const regex = /\{(\d+)(?:_\w+)?\}/g
  let lastIndex = 0
  let match
  while ((match = regex.exec(str)) !== null) {
    segments.push(str.slice(lastIndex, match.index))
    indices.push(parseInt(match[1], 10))
    lastIndex = match.index + match[0].length
  }
  segments.push(str.slice(lastIndex))
  return { s: segments, i: indices }
}

/** @returns {Promise<void>} */
export async function writeMessages() {
  if (process.env.CLEAN === '1') {
    cleanTranslations()
  }

  await sharedMessages.writeAll()
  await messagesJson.writeAll()

  /** @type {Record<string, Record<string, { s: string[]; i: number[] }>>} */
  const messagesOut = {}
  /** @type {Record<string, Record<string, Record<string, { s: string[]; i: number[] }>>>} */
  const pluralsOut = {}

  for (const lang of supportedLanguages) {
    const langData = messagesJson.storage[lang]
    /** @type {Record<string, { s: string[]; i: number[] }>} */
    const simple = {}
    /** @type {Record<string, Record<string, { s: string[]; i: number[] }>>} */
    const plural = {}

    for (const id in langData) {
      const value = langData[id]
      if (typeof value === 'string') {
        simple[id] = preprocessPlaceholderString(value)
      } else if (typeof value === 'object' && !Array.isArray(value)) {
        /** @type {Record<string, { s: string[]; i: number[] }>} */
        const forms = {}
        for (const rule in value) {
          forms[rule] = preprocessPlaceholderString(value[rule])
        }
        plural[id] = forms
      }
    }

    messagesOut[lang] = simple
    pluralsOut[lang] = plural
  }

  const sharedIds = Object.fromEntries(
    Object.entries(sharedMessages.storage[sourceCodeLang]).map(([id, token]) => [id, templateToSharedId(id)]),
  )

  await fs.writeFile(
    path.join('src/lib/assets', 'lang-messages.ts'),
    `
/* eslint-ignore */
/* i18n-ignore */
// Autogenerated by translate plugin

type Language = string
type MessageId = string

export const extractedSharedMessagesIds: Record<MessageId, string> = ${JSON.stringify(sharedIds, null, 2)}

/**
 * Preprocessed simple messages.
 * Structure: { s: string[], i: number[] }
 */
export const extractedTranslatedMessages: Record<Language, Record<MessageId, { s: string[], i: number[] }>> = ${JSON.stringify(messagesOut, null, 2)}

/**
 * Preprocessed plural messages.
 * Structure: Record<PluralRule, { s: string[], i: number[] }>
 */
export const extractedTranslatedPlurals: Record<Language, Record<MessageId, Record<string, { s: string[], i: number[] }>>> = ${JSON.stringify(pluralsOut, null, 2)}
`.replaceAll('\\\\n', '\\n'),
  )
}

/**
 * Converts a placeholder-based ID into a valid Minecraft .lang token.
 *
 * @param {string} id
 * @returns {string}
 */
function templateToSharedId(id) {
  return (
    'script.shared.' +
    id
      .toLowerCase()
      .replace(/§./g, '')
      .replace(/\{(\d+)(?:_\w+)?\}/g, '_$1_')
      .replace(/\\n/g, '_')
      .replace(/\s/g, '_')
      .replace(/[^a-zA-Zа-яА-Я.$_0-9]/g, '_')
      .replace(/\.+/g, '.')
      .replace(/_+/g, '_')
  )
}

/** @type {Record<string, string[]>} */
const plurals = Object.fromEntries(
  supportedLanguages.map(e => [e, new Intl.PluralRules(e.replace('_', '-')).resolvedOptions().pluralCategories]),
)

/**
 * Adds or updates a translation entry.
 *
 * @param {string} id - The message ID with placeholders, e.g. "Вы добыли {0_amount} из {1_needed}"
 * @param {boolean} shared
 * @param {boolean} plural
 */
export function addTranslation(id, shared, plural) {
  const sourcePrev = messagesJson.storage[sourceCodeLang][id]

  if (plural) {
    const sourceCategories = plurals[sourceCodeLang]
    const defaultPlurals = Object.fromEntries(sourceCategories.map(c => [c, id]))
    messagesJson.storage[sourceCodeLang][id] = {
      ...defaultPlurals,
      ...(sourcePrev && typeof sourcePrev === 'object' && !Array.isArray(sourcePrev) ? sourcePrev : {}),
    }
  } else {
    messagesJson.storage[sourceCodeLang][id] = id
  }

  for (const lang of supportedLanguages) {
    if (lang === sourceCodeLang) continue
    const prev = messagesJson.storage[lang][id]
    if (plural) {
      if (prev === undefined || (typeof prev === 'object' && !Array.isArray(prev))) {
        const langCategories = plurals[lang]
        const defaultPlurals = Object.fromEntries(langCategories.map(c => [c, id]))
        messagesJson.storage[lang][id] = {
          ...defaultPlurals,
          ...(typeof prev === 'object' ? prev : {}),
        }
      } else {
        throw new Error(`Plural key conflict for ${id} in ${lang}`)
      }
    } else {
      if (prev === undefined) messagesJson.storage[lang][id] = id
    }
  }

  if (shared || plural) {
    for (const lang of supportedLanguages) {
      const translation = messagesJson.storage[lang][id]
      if (typeof translation === 'string') {
        sharedMessages.storage[lang][id] = translation.replace(/\{(\d+)(?:_\w+)?\}/g, '%s')
      } else if (translation && typeof translation === 'object') {
        for (const rule in translation) {
          sharedMessages.storage[lang][`${id}.${rule}`] = translation[rule].replace(/\{(\d+)(?:_\w+)?\}/g, '%s')
        }
      }
    }
  }
}
