import 'lib'

import './anticheat/index'
import './chat/chat'
import './commands/index'
import './indicator/index'
import './places/dungeons/command'
import './places/dungeons/warden'
import './places/stone-quarry/index'
import './pvp/import'
import './survival/import'
import './test/test'
import './world-edit/builder'
import './world-edit/import'

import 'lib/load/message2'
