import 'lib'

// import '../test/test'
import './chat/chat'
import './commands/index'
import './indicator/index'
import './places/dangeons/command'
import './places/stone-quarry/index'
import './pvp/import'
import './survival/import'
import './test/test'
import './world-edit/builder'
import './world-edit/import'

import 'lib/load/message2'
