import './class/WorldEdit.js'
import './class/WorldEditTool.js'
import './commands/general/desel.js'
import './commands/general/id.js'
import './commands/general/item.js'
import './commands/general/redo.js'
import './commands/general/undo.js'
import './commands/general/we.js'

import './commands/selection/chunk.js'
import './commands/selection/expand.js'
import './commands/selection/hpos1.js'
import './commands/selection/hpos2.js'
import './commands/selection/pos1.js'
import './commands/selection/pos2.js'
import './commands/selection/size.js'

import './commands/region/set.js'

import './commands/clipboard/copy.js'
import './commands/clipboard/paste.js'

import './tools/brush.js'
import './tools/clipboard.js'
import './tools/nylium.js'
import './tools/shovel.js'
import './tools/smooth.js'
import './tools/tool.js'
import './tools/wand.js'
