import './Features/base.js'
import './Features/baseMenu.js'
import './Features/explosibleFireworks.js'
import './Features/fireballAndIceBomb.js'
import './Features/menu.js'
import './Features/quartz.js'
import './Features/raid.js'
import './Features/randomTeleport.js'
import './Features/sidebar.js'
import './Features/throwableTnt.js'

import './Place/Anarchy.js'
import './Place/Mineshaft.js'
import './Place/Spawn.js'
import './Place/StoneQuarry.js'
import './Place/TechCity.js'
import './Place/VillafeOfExplorers.js'
import './Place/VillageOfMiners.js'

import './Quests/index.js'

import './config.js'
