import '../Features/base.js'
import '../Features/baseMenu.js'
import '../Features/breakPlaceOutsideOfRegion.js'
import '../Features/death.js'
import '../Features/explosibleFireworks.js'
import '../Features/fireballAndIceBomb.js'
import '../Features/menu.js'
import '../Features/money.js'
import '../Features/pickaxe.js'
import '../Features/quartz.js'
import '../Features/raid.js'
import '../Features/randomTeleport.js'
import '../Features/sidebar.js'
import '../Features/throwableTnt.js'

import '../Places/Anarchy.js'
import '../Places/Mineshaft.js'
import '../Places/Spawn.js'
import '../Places/StoneQuarry.js'
import '../Places/TechCity.js'
import '../Places/VillafeOfExplorers.js'
import '../Places/VillageOfMiners.js'

import '../Quests/index.js'

import './guard.js'
import './stats.js'
