import './Featuress/base.js'
import './Featuress/baseMenu.js'
import './Featuress/explosibleFireworks.js'
import './Featuress/fireballAndIceBomb.js'
import './Featuress/menu.js'
import './Featuress/raid.js'
import './Featuress/randomTeleport.js'
import './Featuress/sidebar.js'
import './Featuress/throwableTnt.js'

import './Place/Anarchy.js'
import './Place/Mineshaft.js'
import './Place/Spawn.js'
import './Place/StoneQuarry.js'
import './Place/TechCity.js'
import './Place/VillafeOfExplorers.js'
import './Place/VillageOfMiners.js'

import './Questss/index.js'

import './config.js'
