import './lib/WorldEdit'
import './lib/WorldEditTool'

import './commands/general/id'
import './commands/general/item'
import './commands/general/redo'
import './commands/general/undo'
import './commands/general/we'

import './commands/selection/chunk'
import './commands/selection/deselect'
import './commands/selection/expand'
import './commands/selection/hpos1'
import './commands/selection/hpos2'
import './commands/selection/pos1'
import './commands/selection/pos2'
import './commands/selection/size'

import './commands/region/copy'
import './commands/region/paste'
import './commands/region/set'

import './commands/camera/visual'

import './tools/brush'
import './tools/clipboard'
import './tools/nylium'
import './tools/shovel'
import './tools/smooth'
import './tools/tool'
import './tools/wand'
