// prettier-ignore
/* eslint-disable */
// This file is autogenerated by script.
// Do not modify manually.
    
export enum Sounds {
  Pay = 'lw.pay',
  Radiation = 'lw.radiation',
  Success = 'lw.success',
  ZoneEnter = 'lw.zone_enter',
  LevelUp = 'random.levelup',
  Click = 'note.hat',
  Fail = 'block.false_permissions',
}
