// prettier-ignore
/* eslint-disable */
// This file is autogenerated by script.
// Do not modify manually.
    
export const Sounds = {
  "lw.pay": "lw.pay",
  "lw.radiation": "lw.radiation",
  "lw.success": "lw.success",
  "lw.zone_enter": "lw.zone_enter"
} as const
