// prettier-ignore
/* eslint-disable */
// This file is autogenerated by script.
// Do not modify manually.
    
export enum Items {
  Blueprint = 'lw:blueprint',
  CannonShell = 'lw:cannon_shell',
  Chip = 'lw:chip',
  CircuitBoard = 'lw:circuit_board',
  Fireball = 'lw:fireball',
  Key = 'lw:key',
  Menu = 'lw:menu',
  Money = 'lw:money',
  WeBrush = 'we:brush',
  WeDash = 'we:dash',
  WeShovel = 'we:shovel',
  WeTool = 'we:tool',
  WeWand = 'we:wand',
  CompassPrefix = 'lw:compass',
}
  
  export const totalCustomItems = 45
