// prettier-ignore
/* eslint-disable */
// This file is autogenerated by tools/build.js.
// Do not modify manually.
    
export enum CustomEntityTypes {
  Cannon = 'lw:cannon',
  Database = 'rubedo:database',
  Fireball = 'lw:fireball',
  Grave = 'lw:grave',
  Loot = 'lw:loot',
  Sit = 'lw:sit',
  FloatingText = 'f:t',
}
