// prettier-ignore
/* eslint-disable */
// This file is autogenerated by tools/build-scripts.ts.
// Do not modify manually.
    
export enum CustomEntityTypes {
  IronGolem = 'lw:iron_golem',
  Slime = 'lw:slime',
  Wither = 'lw:wither',
  Cannon = 'lw:cannon',
  Database = 'rubedo:database',
  Fireball = 'lw:fireball',
  Grave = 'lw:grave',
  Loot = 'lw:loot',
  Sit = 'lw:sit',
  FloatingText = 'f:t',
  FloatingTextNpc = 'f:t_npc',
}
