export const emoji = {
  money: '',
  leaf: '',
  online: '',
  food: '',
  armor: '',
  pickaxe: '',
  minecoin: '',
  token: '',
  shield: {
    green: '',
    yellow: '',
  },
  custom: {
    socials: {
      discord: String.fromCharCode(0xe110),
      youtube: String.fromCharCode(0xe111),
      telegram: String.fromCharCode(0xe112),
      instagram: String.fromCharCode(0xe113),
      twitch: String.fromCharCode(0xe114),
    },
    armor: {
      leather: String.fromCharCode(0xe120),
      chainmail: String.fromCharCode(0xe121),
      golden: String.fromCharCode(0xe122),
      iron: String.fromCharCode(0xe123),
      diamond: String.fromCharCode(0xe124),
      netherite: String.fromCharCode(0xe125),
    },
    swords: {
      wooden: String.fromCharCode(0xe130),
      stone: String.fromCharCode(0xe131),
      golden: String.fromCharCode(0xe132),
      iron: String.fromCharCode(0xe133),
      diamond: String.fromCharCode(0xe134),
      netherite: String.fromCharCode(0xe135),
    },
    kill: String.fromCharCode(0xe165),
    sword: String.fromCharCode(0xe164),
  },
  buttons: {
    code_builder: '',
    immersive_reader: '',
    xbox: {
      a: '',
      b: '',
      x: '',
      y: '',
      lb: '',
      rb: '',
      lt: '',
      rt: '',
      select: '',
      start: '',
      stick_left: '',
      stick_right: '',
      dpad_left: '',
      dpad_right: '',
      dpad_up: '',
      dpad_down: '',
    },
    playstation: {
      cross: '',
      circle: '',
      square: '',
      triangle: '',
      l1: '',
      r1: '',
      l2: '',
      r2: '',
      select: '',
      start: '',
      stick_left: '',
      stick_right: '',
      dpad_left: '',
      dpad_right: '',
      dpad_up: '',
      dpad_down: '',
    },
    switch: {
      'a': '',
      'b': '',
      'x': '',
      'y': '',
      'l': '',
      'r': '',
      'zl': '',
      'zr': '',
      '-': '',
      '+': '',
      'stick_left': '',
      'stick_right': '',
      'dpad_left': '',
      'dpad_right': '',
      'dpad_up': '',
      'dpad_down': '',
    },
    windows: {
      mouse_left: '',
      mouse_right: '',
      mouse_middle: '',
      arrow_left: '',
      arrow_right: '',
      arrow_foward: '',
      arrow_backward: '',
      jump: '',
      crouch: '',
      fly_up: '',
      fly_down: '',
    },
    windows_mr: {
      grab_left: '',
      grab_right: '',
      menu: '',
      stick_left: '',
      stick_right: '',
      touchpad_left: '',
      touchpad_horizontal_left: '',
      touchpad_vertical_left: '',
      touchpad_right: '',
      touchpad_horizontal_right: '',
      touchpad_vertical_right: '',
      trigger_left: '',
      trigger_right: '',
      windows: '',
    },
    rift: {
      0: '',
      a: '',
      b: '',
      grab_left: '',
      grab_right: '',
      stick_left: '',
      stick_right: '',
      trigger_left: '',
      trigger_right: '',
      x: '',
      y: '',
    },
  },
}
