// prettier-ignore
/* eslint-disable */
// This file is autogenerated by script.
// Do not modify manually.

export const enchantmentsJson = {
  "files": 10,
  "items": 267,
  "levels": {
    "protection": {
      "minecraft:iron_helmet": 8,
      "minecraft:iron_chestplate": 8,
      "minecraft:iron_leggings": 8,
      "minecraft:iron_boots": 8,
      "minecraft:diamond_helmet": 9,
      "minecraft:diamond_chestplate": 9,
      "minecraft:diamond_leggings": 9,
      "minecraft:diamond_boots": 9,
      "minecraft:netherite_helmet": 10,
      "minecraft:netherite_chestplate": 10,
      "minecraft:netherite_leggings": 10,
      "minecraft:netherite_boots": 10
    },
    "fire_protection": {
      "minecraft:iron_helmet": 8,
      "minecraft:iron_chestplate": 8,
      "minecraft:iron_leggings": 8,
      "minecraft:iron_boots": 8,
      "minecraft:diamond_helmet": 9,
      "minecraft:diamond_chestplate": 9,
      "minecraft:diamond_leggings": 9,
      "minecraft:diamond_boots": 9,
      "minecraft:netherite_helmet": 10,
      "minecraft:netherite_chestplate": 10,
      "minecraft:netherite_leggings": 10,
      "minecraft:netherite_boots": 10
    },
    "blast_protection": {
      "minecraft:iron_helmet": 8,
      "minecraft:iron_chestplate": 8,
      "minecraft:iron_leggings": 8,
      "minecraft:iron_boots": 8,
      "minecraft:diamond_helmet": 9,
      "minecraft:diamond_chestplate": 9,
      "minecraft:diamond_leggings": 9,
      "minecraft:diamond_boots": 9,
      "minecraft:netherite_helmet": 10,
      "minecraft:netherite_chestplate": 10,
      "minecraft:netherite_leggings": 10,
      "minecraft:netherite_boots": 10
    },
    "projectile_protection": {
      "minecraft:iron_helmet": 8,
      "minecraft:iron_chestplate": 8,
      "minecraft:iron_leggings": 8,
      "minecraft:iron_boots": 8,
      "minecraft:diamond_helmet": 9,
      "minecraft:diamond_chestplate": 9,
      "minecraft:diamond_leggings": 9,
      "minecraft:diamond_boots": 9,
      "minecraft:netherite_helmet": 10,
      "minecraft:netherite_chestplate": 10,
      "minecraft:netherite_leggings": 10,
      "minecraft:netherite_boots": 10
    },
    "sharpness": {
      "minecraft:iron_sword": 8,
      "minecraft:diamond_sword": 9,
      "minecraft:netherite_sword": 10
    },
    "power": {
      "minecraft:bow": 20
    }
  }
} as const

