// prettier-ignore
/* eslint-disable */
// This file is autogenerated by script.
// Do not modify manually.
    
export const enchantmentsJson = {
  "files": 5,
  "items": 116,
  "levels": {
    "protection": {
      "minecraft:iron_helmet": 5,
      "minecraft:iron_chestplate": 5,
      "minecraft:iron_leggings": 5,
      "minecraft:iron_boots": 5,
      "minecraft:diamond_helmet": 5,
      "minecraft:diamond_chestplate": 5,
      "minecraft:diamond_leggings": 5,
      "minecraft:diamond_boots": 5,
      "minecraft:netherite_helmet": 5,
      "minecraft:netherite_chestplate": 5,
      "minecraft:netherite_leggings": 5,
      "minecraft:netherite_boots": 5,
      "minecraft:enchanted_book": 5
    },
    "fire_protection": {
      "minecraft:iron_helmet": 5,
      "minecraft:iron_chestplate": 5,
      "minecraft:iron_leggings": 5,
      "minecraft:iron_boots": 5,
      "minecraft:diamond_helmet": 5,
      "minecraft:diamond_chestplate": 5,
      "minecraft:diamond_leggings": 5,
      "minecraft:diamond_boots": 5,
      "minecraft:netherite_helmet": 5,
      "minecraft:netherite_chestplate": 5,
      "minecraft:netherite_leggings": 5,
      "minecraft:netherite_boots": 5,
      "minecraft:enchanted_book": 5
    },
    "blast_protection": {
      "minecraft:iron_helmet": 5,
      "minecraft:iron_chestplate": 5,
      "minecraft:iron_leggings": 5,
      "minecraft:iron_boots": 5,
      "minecraft:diamond_helmet": 5,
      "minecraft:diamond_chestplate": 5,
      "minecraft:diamond_leggings": 5,
      "minecraft:diamond_boots": 5,
      "minecraft:netherite_helmet": 5,
      "minecraft:netherite_chestplate": 5,
      "minecraft:netherite_leggings": 5,
      "minecraft:netherite_boots": 5,
      "minecraft:enchanted_book": 5
    },
    "projectile_protection": {
      "minecraft:iron_helmet": 5,
      "minecraft:iron_chestplate": 5,
      "minecraft:iron_leggings": 5,
      "minecraft:iron_boots": 5,
      "minecraft:diamond_helmet": 5,
      "minecraft:diamond_chestplate": 5,
      "minecraft:diamond_leggings": 5,
      "minecraft:diamond_boots": 5,
      "minecraft:netherite_helmet": 5,
      "minecraft:netherite_chestplate": 5,
      "minecraft:netherite_leggings": 5,
      "minecraft:netherite_boots": 5,
      "minecraft:enchanted_book": 5
    },
    "sharpness": {
      "minecraft:iron_sword": 8,
      "minecraft:diamond_sword": 9,
      "minecraft:netherite_sword": 10,
      "minecraft:enchanted_book": 10
    },
    "efficiency": {
      "minecraft:iron_pickaxe": 8,
      "minecraft:diamond_pickaxe": 9,
      "minecraft:netherite_pickaxe": 10,
      "minecraft:enchanted_book": 10
    },
    "power": {
      "minecraft:bow": 20,
      "minecraft:enchanted_book": 20
    }
  }
} as const
