// prettier-ignore
/* eslint-disable */
// This file is autogenerated by tools/build.ts.
// Do not modify manually.
    
export const playerJson = {
  "format_version": "1.17.10",
  "minecraft:entity": {
    "description": {
      "identifier": "minecraft:player",
      "is_spawnable": false,
      "is_summonable": true,
      "is_experimental": false,
      "properties": {
        // used in RP/entities/player.json
        "lw:minimap": {
          "type": "bool",
          "default": false,
          "client_sync": true
        },

        "lw:newbie": {
          "type": "bool",
          "default": false,
          "client_sync": false
        },

        "lw:minigame_team": {
          "type": "enum",
          "values": ["no", "green", "red", "blue", "yellow"],
          "default": "no",
          "client_sync": false
        },

        "lw:minimap_npc_1_x": {
          "type": "int",
          "default": -20000,
          "range": [-20000, 20000],
          "client_sync": true
        },
        "lw:minimap_npc_1_z": {
          "type": "int",
          "default": -20000,
          "range": [-20000, 20000],
          "client_sync": true
        },
        "lw:minimap_npc_2_x": {
          "type": "int",
          "default": -20000,
          "range": [-20000, 20000],
          "client_sync": true
        },
        "lw:minimap_npc_2_z": {
          "type": "int",
          "default": -20000,
          "range": [-20000, 20000],
          "client_sync": true
        }
      }
    },
    "component_groups": {
      "spawn": {
        "minecraft:spell_effects": {
          "add_effects": [
            {
              "effect": "instant_health",
              "duration": 3,
              "amplifier": 255,
              "visible": false,
              "display_on_screen_animation": false
            },
            {
              "effect": "weakness",
              "duration": 3,
              "amplifier": 255,
              "visible": false,
              "display_on_screen_animation": false
            },
            {
              "effect": "resistance",
              "duration": 3,
              "amplifier": 255,
              "visible": false,
              "display_on_screen_animation": true
            },
            {
              "effect": "fire_resistance",
              "duration": 3,
              "amplifier": 255,
              "visible": false,
              "display_on_screen_animation": false
            }
          ]
        }
      },
      "safezone": {
        "minecraft:spell_effects": {
          "add_effects": [
            {
              "effect": "weakness",
              "duration": 1,
              "amplifier": 255,
              "visible": false,
              "display_on_screen_animation": false
            },
            {
              "effect": "resistance",
              "duration": 1,
              "amplifier": 255,
              "visible": false,
              "display_on_screen_animation": true
            },
            {
              "effect": "fire_resistance",
              "duration": 1,
              "amplifier": 255,
              "visible": false,
              "display_on_screen_animation": false
            }
          ]
        }
      },
      "warn": {
        "minecraft:spell_effects": {
          "add_effects": [
            {
              "effect": "resistance",
              "duration": 1,
              "amplifier": 1,
              "visible": false,
              "display_on_screen_animation": true
            }
          ]
        }
      },
      "not_in_spawn": {
        "minecraft:spell_effects": {
          "remove_effects": ["instant_health", "weakness", "resistance", "saturation", "fire_resistance"]
        }
      },
      "kick": {
        "minecraft:instant_despawn": {},
        "minecraft:explode": {}
      },
      "minecraft:add_bad_omen": {
        "minecraft:spell_effects": {
          "add_effects": [
            {
              "effect": "bad_omen",
              "duration": 6000,
              "display_on_screen_animation": true
            }
          ]
        },
        "minecraft:timer": {
          "time": [0.0, 0.0],
          "looping": false,
          "time_down_event": {
            "event": "minecraft:clear_add_bad_omen",
            "target": "self"
          }
        }
      },
      "minecraft:clear_bad_omen_spell_effect": {
        "minecraft:spell_effects": {}
      },
      "minecraft:raid_trigger": {
        "minecraft:raid_trigger": {
          "triggered_event": {
            "event": "minecraft:remove_raid_trigger",
            "target": "self"
          }
        },
        "minecraft:spell_effects": {
          "remove_effects": "bad_omen"
        }
      }
    },
    "components": {
      "minecraft:type_family": {
        "family": ["player"]
      },
      "minecraft:is_hidden_when_invisible": {},
      "minecraft:loot": {
        "table": "loot_tables/empty.json"
      },
      "minecraft:collision_box": {
        "width": 0.6,
        "height": 1.8
      },
      "minecraft:can_climb": {},
      "minecraft:movement": {
        "value": 0.1
      },
      "minecraft:hurt_on_condition": {
        "damage_conditions": [
          {
            "filters": {
              "test": "in_lava",
              "subject": "self",
              "operator": "==",
              "value": true
            },
            "cause": "lava",
            "damage_per_tick": 4
          }
        ]
      },
      "minecraft:attack": {
        "damage": 1
      },
      "minecraft:player.saturation": {
        "value": 20
      },
      "minecraft:player.exhaustion": {
        "value": 0,
        "max": 4
      },
      "minecraft:player.level": {
        "value": 0,
        "max": 24791
      },
      "minecraft:player.experience": {
        "value": 0,
        "max": 1
      },
      "minecraft:breathable": {
        "total_supply": 15,
        "suffocate_time": -1,
        "inhale_time": 3.75,
        "generates_bubbles": false
      },
      "minecraft:nameable": {
        "always_show": true,
        "allow_name_tag_renaming": false
      },
      "minecraft:physics": {},
      "minecraft:pushable": {
        "is_pushable": false,
        "is_pushable_by_piston": true
      },
      "minecraft:insomnia": {
        "days_until_insomnia": 3
      },
      "minecraft:rideable": {
        "seat_count": 2,
        "family_types": ["parrot_tame"],
        "pull_in_entities": true,
        "seats": [
          {
            "position": [0.4, -0.2, -0.1],
            "min_rider_count": 0,
            "max_rider_count": 0,
            "lock_rider_rotation": 0
          },
          {
            "position": [-0.4, -0.2, -0.1],
            "min_rider_count": 1,
            "max_rider_count": 2,
            "lock_rider_rotation": 0
          }
        ]
      },
      "minecraft:conditional_bandwidth_optimization": {},
      "minecraft:block_climber": {},
      "minecraft:environment_sensor": {
        "triggers": [
          {
            "filters": {
              "all_of": [
                {
                  "test": "has_mob_effect",
                  "subject": "self",
                  "value": "bad_omen"
                },
                {
                  "test": "is_in_village",
                  "subject": "self",
                  "value": true
                }
              ]
            },
            "event": "minecraft:trigger_raid"
          },

          {
            "filters": {
              "all_of": [
                {
                  "test": "has_container_open"
                }
              ]
            },
            "event": "player:has_container_open"
          },
          {
            "filters": {
              "none_of": [
                {
                  "test": "has_container_open"
                }
              ]
            },
            "event": "player:no_container_open"
          }
        ]
      },
      "minecraft:damage_sensor": {
        "triggers": [
          {
            "on_damage": {
              "filters": {
                "all_of": [
                  {
                    "test": "has_tag",
                    "subject": "self",
                    "value": "protected"
                  }
                ]
              }
            },
            "deals_damage": false
          },
          {
            "on_damage": {
              "filters": {
                "all_of": [
                  { "all_of": [{ "test": "bool_property", "domain": "lw:newbie" }] },
                  {
                    "any_of": [
                      { "test": "is_family", "subject": "other", "value": "player" },
                      { "test": "has_damage", "value": "fire_tick" }
                    ]
                  }
                ]
              }
            },
            "deals_damage": false //if all of these filters evaluate to true in the current attack interaction, the target will not be hurt.
          },
          {
            "on_damage": {
              "filters": {
                "any_of": [
                  {
                    "all_of": [
                      { "test": "enum_property", "domain": "lw:can_climb", "value": "green" },
                      { "test": "enum_property", "domain": "lw:can_climb", "value": "green" }
                    ]
                  },
                  {
                    "all_of": [
                      { "test": "enum_property", "domain": "lw:can_climb", "value": "blue" },
                      { "test": "enum_property", "domain": "lw:can_climb", "value": "blue" }
                    ]
                  },
                  {
                    "all_of": [
                      { "test": "enum_property", "domain": "lw:can_climb", "value": "red" },
                      { "test": "enum_property", "domain": "lw:can_climb", "value": "red" }
                    ]
                  },
                  {
                    "all_of": [
                      { "test": "enum_property", "domain": "lw:can_climb", "value": "yellow" },
                      { "test": "enum_property", "domain": "lw:can_climb", "value": "yellow" }
                    ]
                  }
                ]
              }
            },
            "deals_damage": false //if any of these filters evaluate to true in the current attack interaction, the target will not be hurt.
          }
        ]
      }
    },
    "events": {
      "player:no_container_open": {},
      "player:has_container_open": {},
      "player:warn": {
        "add": {
          "component_groups": ["warn"]
        }
      },
      "player:spawn": {
        "add": {
          "component_groups": ["spawn"]
        }
      },
      "player:safezone": {
        "add": {
          "component_groups": ["safezone"]
        }
      },
      "player:not_in_spawn": {
        "add": {
          "component_groups": ["notspawn"]
        }
      },
      "player:portal": {},
      "player:kick": {
        "add": {
          "component_groups": ["kick"]
        }
      },
      "minecraft:gain_bad_omen": {
        "add": {
          "component_groups": ["minecraft:add_bad_omen"]
        }
      },
      "minecraft:clear_add_bad_omen": {
        "remove": {
          "component_groups": ["minecraft:add_bad_omen"]
        },
        "add": {
          "component_groups": ["minecraft:clear_bad_omen_spell_effect"]
        }
      },
      "minecraft:trigger_raid": {
        "add": {
          "component_groups": ["minecraft:raid_trigger"]
        }
      },
      "minecraft:remove_raid_trigger": {
        "remove": {
          "component_groups": ["minecraft:raid_trigger"]
        }
      }
    }
  }
} as const
  
export const PlayerProperties = Object.fromEntries(
  Object.keys(playerJson['minecraft:entity'].description.properties).map(e => [e, e]),
)

export const PlayerEvents = Object.fromEntries(Object.keys(playerJson['minecraft:entity'].events).map(e => [e, e]))

