// prettier-ignore
/* eslint-disable */
// This file is autogenerated by script.
// Do not modify manually.
    

import { MinecraftItemTypes } from '@minecraft/vanilla-data'
    
export const shopFormula = {
  formula: (maxCount: number, x: number, minPrice: number, k: number) => minPrice + maxCount * k - x * x / maxCount * k,  
  shop: {
  [MinecraftItemTypes.Emerald]: {
    "maxCount": 100,
    "minPrice": 8000,
    "k": 5,
    "defaultCount": 50
  },
  [MinecraftItemTypes.OakLog]: {
    "maxCount": 10000,
    "minPrice": 8,
    "k": 0.0001,
    "defaultCount": 5000
  },
  [MinecraftItemTypes.OakPlanks]: {
    "maxCount": 10000,
    "minPrice": 2,
    "k": 0.0001,
    "defaultCount": 5000
  },
  [MinecraftItemTypes.Calcite]: {
    "maxCount": 1000,
    "minPrice": 2,
    "k": 0.01,
    "defaultCount": 500
  },
  [MinecraftItemTypes.CobbledDeepslate]: {
    "maxCount": 10000,
    "minPrice": 2,
    "k": 0.0002,
    "defaultCount": 500
  },
  [MinecraftItemTypes.Tuff]: {
    "maxCount": 1000,
    "minPrice": 2,
    "k": 0.006,
    "defaultCount": 500
  },
  [MinecraftItemTypes.Granite]: {
    "maxCount": 10000,
    "minPrice": 2,
    "k": 0.0007,
    "defaultCount": 500
  },
  [MinecraftItemTypes.Diorite]: {
    "maxCount": 10000,
    "minPrice": 2,
    "k": 0.0007,
    "defaultCount": 500
  },
  [MinecraftItemTypes.Andesite]: {
    "maxCount": 10000,
    "minPrice": 2,
    "k": 0.0007,
    "defaultCount": 500
  },
  [MinecraftItemTypes.Cobblestone]: {
    "maxCount": 10000,
    "minPrice": 0.1,
    "k": 0.0001,
    "defaultCount": 500
  },
  [MinecraftItemTypes.Diamond]: {
    "maxCount": 1000,
    "minPrice": 500,
    "k": 0.5,
    "defaultCount": 500
  },
  [MinecraftItemTypes.GoldIngot]: {
    "maxCount": 1000,
    "minPrice": 250,
    "k": 0.1,
    "defaultCount": 500
  },
  [MinecraftItemTypes.IronIngot]: {
    "maxCount": 20000,
    "minPrice": 50,
    "k": 0.001,
    "defaultCount": 10000
  },
  [MinecraftItemTypes.LapisLazuli]: {
    "maxCount": 1000,
    "minPrice": 2000,
    "k": 0.5,
    "defaultCount": 500
  },
  [MinecraftItemTypes.Coal]: {
    "maxCount": 30000,
    "minPrice": 1,
    "k": 0.0001,
    "defaultCount": 15000
  },
  [MinecraftItemTypes.CopperIngot]: {
    "maxCount": 30000,
    "minPrice": 6,
    "k": 0.001,
    "defaultCount": 15000
  },
  [MinecraftItemTypes.Redstone]: {
    "maxCount": 40000,
    "minPrice": 1.5,
    "k": 0.001,
    "defaultCount": 15000
  },
  [MinecraftItemTypes.Cod]: {
    "maxCount": 1000,
    "minPrice": 10,
    "k": 0.01,
    "defaultCount": 100
  },
  [MinecraftItemTypes.Chicken]: {
    "maxCount": 1000,
    "minPrice": 10,
    "k": 0.01,
    "defaultCount": 100
  },
  [MinecraftItemTypes.Beef]: {
    "maxCount": 1000,
    "minPrice": 10,
    "k": 0.01,
    "defaultCount": 100
  },
  [MinecraftItemTypes.Mutton]: {
    "maxCount": 1000,
    "minPrice": 10,
    "k": 0.01,
    "defaultCount": 100
  },
  [MinecraftItemTypes.Porkchop]: {
    "maxCount": 1000,
    "minPrice": 10,
    "k": 0.01,
    "defaultCount": 100
  },
  [MinecraftItemTypes.Rabbit]: {
    "maxCount": 1000,
    "minPrice": 10,
    "k": 0.01,
    "defaultCount": 100
  },
  [MinecraftItemTypes.Salmon]: {
    "maxCount": 1000,
    "minPrice": 10,
    "k": 0.01,
    "defaultCount": 100
  }
}
}
