// prettier-ignore
/* eslint-disable */
// This file is autogenerated by script.
// Do not modify manually.
    

export interface StructureFile {
  size: Vector3,
  chestPositions: Vector3[]
  enderChestPositions: Vector3[]
  structureVoidPoisitions: Vector3[]
  shulkers: { loc: Vector3, inv: { typeId: string, amount: number, slot: number }[] }[]
}

export enum StructureRootId {
  CustomEnchantments = 'mystructure:custom_enchantments',
  FloatingItem = 'mystructure:floating_item',
  SpawnV1 = 'mystructure:spawn_v1',
}

export enum StructureDungeonsId {
  Avanpost = 'mystructure:dungeons/avanpost',
  GasStation1 = 'mystructure:dungeons/gas_station_1',
  GasStation2 = 'mystructure:dungeons/gas_station_2',
  GasStation3 = 'mystructure:dungeons/gas_station_3',
  GasStation4 = 'mystructure:dungeons/gas_station_4',
  GasStationGarage = 'mystructure:dungeons/gas_station_garage',
}

export enum StructureTestId {
  Empty = 'mystructure:test/empty',
  Flat5x5x5 = 'mystructure:test/flat_5x5x5',
}

export type StructureId = StructureRootId | StructureDungeonsId | StructureTestId

export const structureFiles: Record<StructureId, StructureFile> = {
  "mystructure:custom_enchantments": {
    "size": {
      "x": 1,
      "y": 1,
      "z": 1
    },
    "chestPositions": [],
    "enderChestPositions": [],
    "structureVoidPoisitions": [],
    "shulkers": []
  },
  "mystructure:dungeons/avanpost": {
    "size": {
      "x": 21,
      "y": 35,
      "z": 21
    },
    "chestPositions": [
      {
        "x": 5,
        "y": 10,
        "z": 6
      },
      {
        "x": 6,
        "y": 10,
        "z": 5
      },
      {
        "x": 6,
        "y": 23,
        "z": 14
      },
      {
        "x": 10,
        "y": 16,
        "z": 14
      },
      {
        "x": 14,
        "y": 10,
        "z": 5
      },
      {
        "x": 14,
        "y": 16,
        "z": 10
      },
      {
        "x": 14,
        "y": 23,
        "z": 6
      },
      {
        "x": 15,
        "y": 10,
        "z": 6
      }
    ],
    "enderChestPositions": [
      {
        "x": 6,
        "y": 23,
        "z": 6
      },
      {
        "x": 14,
        "y": 23,
        "z": 14
      }
    ],
    "structureVoidPoisitions": [],
    "shulkers": [
      {
        "loc": {
          "x": 4,
          "y": 23,
          "z": 10
        },
        "inv": [
          {
            "amount": 2,
            "typeId": "minecraft:vex_spawn_egg",
            "slot": 0
          },
          {
            "amount": 1,
            "typeId": "minecraft:vindicator_spawn_egg",
            "slot": 1
          },
          {
            "amount": 1,
            "typeId": "minecraft:witch_spawn_egg",
            "slot": 2
          }
        ]
      },
      {
        "loc": {
          "x": 6,
          "y": 1,
          "z": 6
        },
        "inv": [
          {
            "amount": 2,
            "typeId": "minecraft:pillager_spawn_egg",
            "slot": 0
          },
          {
            "amount": 1,
            "typeId": "minecraft:vindicator_spawn_egg",
            "slot": 1
          }
        ]
      },
      {
        "loc": {
          "x": 6,
          "y": 16,
          "z": 6
        },
        "inv": [
          {
            "amount": 2,
            "typeId": "minecraft:vex_spawn_egg",
            "slot": 0
          },
          {
            "amount": 1,
            "typeId": "minecraft:witch_spawn_egg",
            "slot": 1
          },
          {
            "amount": 1,
            "typeId": "minecraft:evoker_spawn_egg",
            "slot": 2
          }
        ]
      },
      {
        "loc": {
          "x": 10,
          "y": 10,
          "z": 10
        },
        "inv": [
          {
            "amount": 1,
            "typeId": "minecraft:vindicator_spawn_egg",
            "slot": 0
          },
          {
            "amount": 1,
            "typeId": "minecraft:ravager_spawn_egg",
            "slot": 1
          },
          {
            "amount": 2,
            "typeId": "minecraft:pillager_spawn_egg",
            "slot": 2
          }
        ]
      },
      {
        "loc": {
          "x": 10,
          "y": 23,
          "z": 4
        },
        "inv": [
          {
            "amount": 2,
            "typeId": "minecraft:vex_spawn_egg",
            "slot": 0
          },
          {
            "amount": 1,
            "typeId": "minecraft:evoker_spawn_egg",
            "slot": 1
          }
        ]
      },
      {
        "loc": {
          "x": 10,
          "y": 23,
          "z": 16
        },
        "inv": [
          {
            "amount": 2,
            "typeId": "minecraft:vex_spawn_egg",
            "slot": 0
          },
          {
            "amount": 1,
            "typeId": "minecraft:vindicator_spawn_egg",
            "slot": 1
          },
          {
            "amount": 2,
            "typeId": "minecraft:pillager_spawn_egg",
            "slot": 2
          }
        ]
      },
      {
        "loc": {
          "x": 14,
          "y": 1,
          "z": 14
        },
        "inv": [
          {
            "amount": 2,
            "typeId": "minecraft:pillager_spawn_egg",
            "slot": 0
          }
        ]
      },
      {
        "loc": {
          "x": 14,
          "y": 16,
          "z": 14
        },
        "inv": [
          {
            "amount": 1,
            "typeId": "minecraft:evoker_spawn_egg",
            "slot": 0
          },
          {
            "amount": 1,
            "typeId": "minecraft:vex_spawn_egg",
            "slot": 1
          },
          {
            "amount": 1,
            "typeId": "minecraft:pillager_spawn_egg",
            "slot": 2
          }
        ]
      }
    ]
  },
  "mystructure:dungeons/gas_station_1": {
    "size": {
      "x": 20,
      "y": 12,
      "z": 22
    },
    "chestPositions": [
      {
        "x": 10,
        "y": 1,
        "z": 13
      },
      {
        "x": 15,
        "y": 1,
        "z": 9
      }
    ],
    "enderChestPositions": [],
    "structureVoidPoisitions": [],
    "shulkers": []
  },
  "mystructure:dungeons/gas_station_2": {
    "size": {
      "x": 18,
      "y": 8,
      "z": 16
    },
    "chestPositions": [
      {
        "x": 3,
        "y": 1,
        "z": 10
      },
      {
        "x": 11,
        "y": 1,
        "z": 5
      }
    ],
    "enderChestPositions": [],
    "structureVoidPoisitions": [],
    "shulkers": []
  },
  "mystructure:dungeons/gas_station_3": {
    "size": {
      "x": 19,
      "y": 10,
      "z": 16
    },
    "chestPositions": [
      {
        "x": 7,
        "y": 1,
        "z": 7
      },
      {
        "x": 14,
        "y": 2,
        "z": 3
      }
    ],
    "enderChestPositions": [],
    "structureVoidPoisitions": [],
    "shulkers": []
  },
  "mystructure:dungeons/gas_station_4": {
    "size": {
      "x": 30,
      "y": 10,
      "z": 20
    },
    "chestPositions": [
      {
        "x": 9,
        "y": 1,
        "z": 13
      },
      {
        "x": 23,
        "y": 2,
        "z": 5
      }
    ],
    "enderChestPositions": [],
    "structureVoidPoisitions": [],
    "shulkers": []
  },
  "mystructure:dungeons/gas_station_garage": {
    "size": {
      "x": 19,
      "y": 12,
      "z": 27
    },
    "chestPositions": [
      {
        "x": 12,
        "y": 1,
        "z": 22
      },
      {
        "x": 16,
        "y": 1,
        "z": 3
      }
    ],
    "enderChestPositions": [],
    "structureVoidPoisitions": [],
    "shulkers": []
  },
  "mystructure:floating_item": {
    "size": {
      "x": 1,
      "y": 1,
      "z": 1
    },
    "chestPositions": [],
    "enderChestPositions": [],
    "structureVoidPoisitions": [],
    "shulkers": []
  },
  "mystructure:spawn_v1": {
    "size": {
      "x": 27,
      "y": 33,
      "z": 40
    },
    "chestPositions": [],
    "enderChestPositions": [],
    "structureVoidPoisitions": [],
    "shulkers": []
  },
  "mystructure:test/empty": {
    "size": {
      "x": 1,
      "y": 1,
      "z": 1
    },
    "chestPositions": [],
    "enderChestPositions": [],
    "structureVoidPoisitions": [],
    "shulkers": []
  },
  "mystructure:test/flat_5x5x5": {
    "size": {
      "x": 5,
      "y": 5,
      "z": 5
    },
    "chestPositions": [],
    "enderChestPositions": [],
    "structureVoidPoisitions": [],
    "shulkers": []
  }
}
