// prettier-ignore
/* eslint-disable */
// This file is autogenerated by script.
// Do not modify manually.

export interface StructureFile {
  size: Vector3,
  chestPositions: Vector3[]
}
export enum StructureId {
  CustomEnchantments = 'mystructure:custom_enchantments',
  DungeonsGasStation1 = 'mystructure:dungeons/gas_station_1',
  DungeonsGasStation2 = 'mystructure:dungeons/gas_station_2',
  DungeonsGasStation3 = 'mystructure:dungeons/gas_station_3',
  DungeonsGasStation4 = 'mystructure:dungeons/gas_station_4',
  DungeonsGasStationGarage = 'mystructure:dungeons/gas_station_garage',
  FloatingItem = 'mystructure:floating_item',
  SpawnV1 = 'mystructure:spawn_v1',
  TestEmpty = 'mystructure:test/empty',
  TestFlat5x5x5 = 'mystructure:test/flat_5x5x5',
}
export const structureFiles: Record<StructureId, StructureFile> = {
  'mystructure:custom_enchantments': {
    size: {
      x: 1,
      y: 1,
      z: 1,
    },
    chestPositions: [],
  },
  'mystructure:dungeons/gas_station_1': {
    size: {
      x: 20,
      y: 12,
      z: 22,
    },
    chestPositions: [
      {
        x: 10,
        y: 1,
        z: 13,
      },
      {
        x: 15,
        y: 1,
        z: 9,
      },
    ],
  },
  'mystructure:dungeons/gas_station_2': {
    size: {
      x: 18,
      y: 8,
      z: 16,
    },
    chestPositions: [],
  },
  'mystructure:dungeons/gas_station_3': {
    size: {
      x: 19,
      y: 10,
      z: 16,
    },
    chestPositions: [
      {
        x: 7,
        y: 1,
        z: 7,
      },
      {
        x: 14,
        y: 2,
        z: 3,
      },
    ],
  },
  'mystructure:dungeons/gas_station_4': {
    size: {
      x: 30,
      y: 10,
      z: 20,
    },
    chestPositions: [
      {
        x: 9,
        y: 1,
        z: 13,
      },
      {
        x: 23,
        y: 2,
        z: 5,
      },
    ],
  },
  'mystructure:dungeons/gas_station_garage': {
    size: {
      x: 19,
      y: 12,
      z: 27,
    },
    chestPositions: [
      {
        x: 12,
        y: 1,
        z: 22,
      },
      {
        x: 16,
        y: 1,
        z: 3,
      },
    ],
  },
  'mystructure:floating_item': {
    size: {
      x: 1,
      y: 1,
      z: 1,
    },
    chestPositions: [],
  },
  'mystructure:spawn_v1': {
    size: {
      x: 27,
      y: 33,
      z: 40,
    },
    chestPositions: [],
  },
  'mystructure:test/empty': {
    size: {
      x: 1,
      y: 1,
      z: 1,
    },
    chestPositions: [],
  },
  'mystructure:test/flat_5x5x5': {
    size: {
      x: 5,
      y: 5,
      z: 5,
    },
    chestPositions: [],
  },
}

