// prettier-ignore
/* eslint-disable */
// This file is autogenerated by script.
// Do not modify manually.
    
export const textureData = {
  "lw:blueprint": "textures/items/blueprint",
  "lw:cannon_shell": "textures/items/cannon_shell",
  "lw:chip": "textures/items/chip",
  "lw:circuit_board": "textures/items/circuit_board",
  "lw:fireball": "textures/items/fireball",
  "lw:key": "textures/blocks/trip_wire_source",
  "lw:menu": "textures/items/totem",
  "lw:money": "textures/items/money",
  "we:brush": "textures/items/brush",
  "we:dash": "textures/items/compass_item",
  "we:debugstick": "textures/items/stick",
  "we:randomizer": "textures/items/name_tag",
  "we:shovel": "textures/items/shovel",
  "we:tool": "textures/items/chain",
  "we:wand": "textures/items/axe"
}
    
export const enchantData: Record<string, boolean | undefined> = {
  "lw:blueprint": false,
  "lw:cannon_shell": false,
  "lw:chip": false,
  "lw:circuit_board": false,
  "lw:fireball": false,
  "lw:key": true,
  "lw:menu": true,
  "lw:money": false,
  "we:brush": true,
  "we:dash": true,
  "we:debugstick": true,
  "we:randomizer": true,
  "we:shovel": true,
  "we:tool": true,
  "we:wand": true
}
