name: scripts
on:
  workflow_dispatch:

  push:
    branches:
      - main
    tags:
      - '!*' # Do not execute on tags
    paths:
      - src/**
      - tools/**
      - yarn.lock
      - .github/workflows/cd-scripts.yml
      - eslint.config.js
      - vitest.config.ts
      - tsconfig.json

  pull_request:

env:
  CI: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          submodules: true

      - run: corepack enable

      - uses: actions/setup-node@v4.0.3
        with:
          node-version: 22

      - run: yarn install --immutable

      - run: node --no-warnings --experimental-strip-types --experimental-transform-types tools/build.ts

      - run: yarn test --run --coverage

      - name: Upload coverage
        # Run only on push on main repo
        if: github.repository == 'LushWay/Scripts' && github.ref == 'refs/heads/main'
        uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage/lcov.info

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          submodules: true

      - run: corepack enable

      - uses: actions/setup-node@v4.0.3
        with:
          node-version: 22

      - run: yarn install --immutable

      - run: node --no-warnings --experimental-strip-types --experimental-transform-types tools/build.ts

      - run: yarn tsc

      - run: yarn eslint src
