name: CI
on:
  workflow_dispatch:

  push:
    branches:
      - main
    tags:
      - '!*' # Do not execute on tags
    paths:
      - src/*
      - yarn.lock
      - .github/workflows/test.yml

  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - run: corepack enable

      - uses: actions/setup-node@master
        with:
          node-version: 22

      - run: yarn install --immutable

      - run: node build

      - run: yarn test --run --coverage

      - uses: paambaati/codeclimate-action@v8.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - run: corepack enable

      - uses: actions/setup-node@master
        with:
          node-version: 22

      - run: yarn install --immutable

      - run: yarn prettier -w src

      - run: yarn eslint src

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    # Run only on push on main repo
    if: github.repository == 'LushWay/Scripts' && github.ref == 'refs/heads/main'
    needs: [test, lint]
    steps:
      - run: echo 'Deploy occurs'
