name: test
on:
  workflow_dispatch:

  push:
    branches:
      - main
    tags:
      - '!*' # Do not execute on tags
    paths:
      - src/*
      - yarn.lock
      - .github/workflows/test.yml

  pull_request:
    paths:
      - '!*.MD'
jobs:
  test:
    name: Test/Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - run: corepack enable
      - uses: actions/setup-node@master
        with:
          node-version: 22

      - run: yarn install --immutable --immutable-cache
      - run: node build
      - run: yarn test --run --coverage
      - uses: paambaati/codeclimate-action@v8.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
